# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf648db3807319c603ebf32cde8cb1836e4f159f72e96de4dd3f3a7d3465257dfe6782d74548f66082ff434e84758bc0e4cde81f13cbc0baddb4578565d13a3e

test:
  secret_key_base: c285fa34b602dfd45dc921592847b0cfc9b88db6ef8331105052b214c83875501d66a71abeb345be94d6add863e0fd6278a6c181f6b32211d94554a925cd573f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
